# Generated by Django 2.0 on 2017-12-10 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_countrydatavalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesTempMaxValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uMonthId', models.IntegerField()),
                ('uTempValue', models.IntegerField()),
                ('uCountryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.Country')),
            ],
        ),
    ]
