# Generated by Django 2.0 on 2017-12-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_countriestempmaxvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countriestempmaxvalue',
            name='uTempValue',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
